title: openSUSE News
email: admin@opensuse.org
description: >-
  openSUSE News site providing newest news from the openSUSE Project
baseurl: ""
url: "https://news.opensuse.org"
sourcecode: "https://github.com/openSUSE/news-o-o"

excerpt_separator: <!--more-->

markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-archives
paginate: 10
paginate_path: '/page/:num/'
permalink: /:year/:month/:day/:title/

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    tag: cattag-archive
    category: cattag-archive

exclude: [README.md, Gemfile, Gemfile.lock, vendor]
